name: odcread
base: core18
version: '0.2'
summary: Reader of ".odc" Oberon compound documents
description: |
  This program converts to plain text "Oberon compound document" binary format,
  used by the BlackBox Component Builder, WinBUGS, and OpenBUGS.

grade: stable
confinement: strict

parts:
  odcread:
    plugin: make
    source: .

apps:
  odcread:
    command: usr/bin/odcread
    plugs:
      - home
      - account-control
